Fix type error in copy_to_source.py
Replace `os.environ.get("BUILD_WORKSPACE_DIRECTORY")`
with `os.environ["BUILD_WORKSPACE_DIRECTORY"]`.

The former may return None if the environment variable is not
set, in which case the code will crash with a TypeError when the
line is run since the result is concatenated with a `pathlib.Path`
object, and is therefore making it impossible to use rules_python_gazelle_plugin along with rules_mypy:

    INFO: Analyzed target //:gazelle_python_manifest.update (63 packages loaded, 10415 targets configured).
    INFO: Found 1 target...
    ERROR: /.../BUILD:52:24: mypy //:gazelle_python_manifest.update failed: (Exit 1): mypy failed: ...
     external/rules_python_gazelle_plugin+/manifest/copy_to_source.py:23: error: Unsupported operand types for / ("None" and "Path")  [operator]
external/rules_python_gazelle_plugin+/manifest/copy_to_source.py:23: note: Left operand is of type "str | None"
    Found 1 error in 1 file (checked 1 source file)
    Target //:gazelle_python_manifest.update failed to build
    Aspect //tools:aspects.bzl%mypy_aspect of //:gazelle_python_manifest.update failed to build

These changes allow rules_mypy users to also use
rules_python_gazelle_plugin without having to work around the
type error.

Now if the environment variable is not set, the code will still crash, but now with an error that better indicates the failed
precondition, i.e. KeyError("BUILD_WORKSPACE_DIRECTORY") rather than TypeError.